branch-defaults:
  default:
    environment: udagram-api-dev
    group_suffix: null
  master:
    environment: udagram-api-dev
    group_suffix: null
environment-defaults:
  udagram-api-dev:
    branch: null
    repository: null
global:
  application_name: udagram-api
  branch: null
  default_ec2_keyname: vockey
  default_platform: Node.js
  default_region: us-east-1
  deploy:
    artifact: www/Archive.zip
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
